### ISSUE TITLE
Application crashes on start when targeted by Inspeckage on LG G4 MM

### ISSUE THREAD

**Issue by cdeletre** [ac-pm/Inspeckage#35]
When I target an application (eg. Firefox, FM radio, any app) with Inspeckage and try to launch it (through Inspeckage or directly from native android launcher) the application immediately crashes with a system error message "The application has stop working".

- Mobile: LG G4 (H815)
- Android version:  6.0
- Kernel version: 3.10.84
- Software version: V20e-208-01
- Xposed framework installed in version 86 for arm64
- Inspeckage version: 1.4.1

Here are logcat with crash of Firefox
[logcat.txt](https://github.com/ac-pm/Inspeckage/files/378214/logcat.txt)

**Comment by ac-pm** [comment]
Hi @cdeletre , the problem is the new android system permission, insted of save the logs on sdcard, now the Inspeckage save on the app folder.

Please try this release that work for me, if it work for you I will commit the changes.

[app-debug-unaligned.apk.zip](https://github.com/ac-pm/Inspeckage/files/379323/app-debug-unaligned.apk.zip)

**Comment by cdeletre** [comment]
Hi,

Thk you I'll try to have alook at on wednesday :) I'll let you know

**Comment by kwatkins** [comment]
Good job ac-pm, that attachment worked for MM.

**Comment by jabbink** [comment]
Works for me (One Plus One on CM13)

**Comment by JhonSumpena** [comment]
Work for me (Asus Zenfone 5 lollipop)

**Comment by cdeletre** [comment]
Hi,

I've just tested this release and it worked for me.

Thank you :)



Cyril

2016-08-18 11:10 GMT+02:00 JhonSumpena <notifications@github.com>:

**Comment by ac-pm** [comment]
Done. Please try v2.0
