### ISSUE TITLE
Inspeckage does not dected that the app is running

### ISSUE THREAD

**Issue by clviper** [ac-pm/Inspeckage#6]
I still could not detect in what circumstances this occurs, but sometimes, the app is running but the webinterface still indicates the app running:false and the most of the information does not appear.

**Comment by ac-pm** [comment]
Look, each time that Inspeckage start, if the target app is running, the app must be restarted for apply hooks correctly. Please, check this case.

**Comment by clviper** [comment]
You are right. Doing that solves the issue.

**Comment by KaniketCode95** [comment]
it still not working for me it still showing me app is running: false

**Comment by jufelka** [comment]
I have the same problem. After the target app started, the web interface shows "the app running:false" and if I tried to reload page I got "ERR_CONNECTION_REFUSED"

**Comment by dedfft** [comment]
" "the app running:false" and if I tried to reload page I got "ERR_CONNECTION_REFUSED""

Exactly the same issue. Any workarounds?

**Comment by DarkSkull91** [comment]
It's just happened to me... any solution?

**Comment by mz135135** [comment]
您的邮件我已经收到！

**Comment by mahmutyazici** [comment]
Hi all, 
Is there any update on this? I'm encountering the exact same error. Inspeckage cannot confirm if the app is running even though it's running. Even after restarting it to apply the hooks correctly, it doesn't work. Additionally, after about a minute, it displays a message that the service has stopped, and Inspeckage has ceased running. I'm using Genymotion on Android 11.

**Comment by HumairaFasih** [comment]
Hi @mahmutyazici 

I'm also running Genymotion on Android 11 and the service does stop every now and then. And even though the app is running it doesn't detect anything.

One note about the service stopping issue is to just go to config and click the APPLY button again in Inspeckage. Wait for it to display whether service has started or stopped a bit longer, because it reports the service status with a delay, so it doesn't synchronise with your clicks. If e.g. you were to click it a lot of times, it would keep changing status with a delay so make sure it displays a service started message before you try to check it in the browser. 

However, can you please let me know if you found a fix for the app running issue? Really need to use this tool for location stuff in an important project. Also, if you have any suggestions for spoofing locations (in a robust way) please suggest that too in case Inspeckage is out of luck with this error.
